version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    networks:
      - app_network
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/backend.db:/app/backend.db  # Выносим базу данных за пределы контейнера
    environment:
      - DATABASE_URL=sqlite:///./backend.db
      - SECRET_KEY=your_super_secret_key

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - app_network
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8500

  bot:
    build:
      context: ./bot
    container_name: bot
    networks:
      - app_network
    depends_on:
      - backend
    environment:
      - BOT_BACKEND_URL=http://backend:8500  # Адрес Backend для бота
      - TELEGRAM_BOT_TOKEN=""  # Токен Telegram
      - FRONTEND_URL=http://frontend:3000
    restart: always

networks:
  app_network:
    driver: bridge

